[Variables]

Blur=1

BackColor=FFFFFF
BackOp=0
BorderColor=000000
BorderOp=128

Cover=#@#Default.png
ColorButton=FFFFFF
ColorStars=#ColorButton#
StarsOp=255

BarColor=F8E71CEE
BarBackColor=FFFFFF40

Font=Trebuchet MS
ColorTrack=FFFFFFFF
ColorArtist=FFFFFFFF
ColorAlbum=FFFFFFFF
ColorTime=FFFFFF99
ColorVol=#ColorButton#A0

ColorBackError=000000CA
ColorError=FFFFFFFF
Invisible=00000001