[Variables]

Blur=1

BackColor=FFFFFF
BackOp=128
BorderColor=EEEEEE
BorderOp=64

Cover=WDefault.png
ColorButton=333333
ColorStars=#ColorButton#
StarsOp=255

BarColor=28458CEE
BarBackColor=11111130

Font=Trebuchet MS
ColorTrack=111111FF
ColorArtist=111111FF
ColorAlbum=111111FF
ColorTime=111111AA
ColorVol=#ColorButton#C0

ColorBackError=FFFFFFAF
ColorError=111111FF
Invisible=00000001