[Variables]

Blur=1

BackColor=111111
BackOp=128
BorderColor=000000
BorderOp=64

Cover=#@#Default.png
ColorButton=FFFFFF
ColorStars=#ColorButton#
StarsOp=255

BarColor=E8A71CEE
BarBackColor=FFFFFF20

Font=Trebuchet MS
ColorTrack=FFFFFFFF
ColorArtist=FFFFFFFF
ColorAlbum=FFFFFFFF
ColorTime=FFFFFF99
ColorVol=#ColorButton#A0

ColorBackError=000000CF
ColorError=FFFFFFFF
Invisible=00000001