[Variables]

Blur=0

BackColor=000000
BackOp=255
BorderColor=000000
BorderOp=64

Cover=#@#Default.png
ColorButton=FFFFFF
ColorStars=#ColorButton#
StarsOp=255

BarColor=E8D71CEE
BarBackColor=FFFFFF20

Font=Trebuchet MS
ColorTrack=FFFFFFFF
ColorArtist=FFFFFFFF
ColorAlbum=FFFFFFFF
ColorTime=FFFFFF99
ColorVol=#ColorButton#A0

ColorBackError=000000EA
ColorError=FFFFFFFF
Invisible=00000001