[Variables]

Blur=0

BackColor=161616
BackOp=248
BorderColor=161616
BorderOp=255

Cover=Default.png
ColorButton=FFFFFF
ColorStars=#ColorButton#
StarsOp=255

BarColor=E8D71CEE
BarBackColor=FFFFFF10

Font=Trebuchet MS
ColorTrack=FFFFFFFF
ColorArtist=FFFFFFFF
ColorAlbum=FFFFFFFF
ColorTime=FFFFFF99
ColorVol=#ColorButton#A0

ColorBackError=000000EA
ColorError=FFFFFFFF
Invisible=00000001