[Variables]

Blur=0

BackColor=FFFFFF
BackOp=255
BorderColor=EEEEEE
BorderOp=64

Cover=WDefault.png
ColorButton=111111
ColorStars=#ColorButton#
StarsOp=255

BarColor=28458CEE
BarBackColor=11111130

Font=Trebuchet MS
ColorTrack=222222FF
ColorArtist=222222FF
ColorAlbum=222222FF
ColorTime=111111AA
ColorVol=#ColorButton#C0

ColorBackError=FFFFFFDF
ColorError=222222FF
Invisible=00000001